#!/bin/bash

# THIS SCRIPT WILL RUN A NEW WAVEPACK DYNAMICS SIMULATION. THE SIMULATION NEEDS AN INPUT FILE TO BE ABLE TO RUN. FIRST, THIS SCRIPT ASKS THE USER FOR THE PATH TO THE INPUT FILE CONTAINING ALL THE SIMULATION PARAMETERS. IF THE FILE DOES NOT EXISTS, THEN THE SCRIPT WILL GENERATE A NEW FILE USING THE INFORMATION GIVEN BY THE USER.


